## Mathemeatics

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])

In [3]:
arr+2

array([3, 4, 5, 6, 7])

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
arr*2

array([ 2,  4,  6,  8, 10])

In [6]:
arr/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [7]:
arr**2

array([ 1,  4,  9, 16, 25])

In [8]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [9]:
np.cos(arr)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [10]:
np.tan(arr)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

### Linear algebra

In [11]:
arr_1 = np.array([1,2,3])
arr_2 = np.array([3,4,5])
arr_1*arr_2

array([ 3,  8, 15])

In [12]:
# matrix multiplication

a = np.ones((2,3), dtype = 'int64')
b = np.full(a.transpose().shape, 2)

In [13]:
a.shape

(2, 3)

In [14]:
b.shape

(3, 2)

In [15]:
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [16]:
a

array([[1, 1, 1],
       [1, 1, 1]])

In [17]:
c = np.matmul(a,b)

In [18]:
np.linalg.det(c)

0.0

In [19]:
np.linalg.det(np.ones((3,3)))

0.0

In [20]:
#determinant
d = np.identity(3)    
np.linalg.det(d)

1.0

In [21]:
np.invert(c)

array([[-7, -7],
       [-7, -7]])

In [22]:
e = np.array([[1,2,3],[4,5,6]])

In [23]:
e.min(axis = 0)

array([1, 2, 3])

In [24]:
e.min(axis = 1)

array([1, 4])

In [25]:
e.max(axis= 0)

array([4, 5, 6])

In [26]:
e.max(axis = 1)

array([3, 6])

In [27]:
np.min(e)

1

In [28]:
np.max(e)

6

In [29]:
x = np.ones((3,4))

In [30]:
x.astype('int64')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [31]:
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
masked_arr = np.random.randint(1,40,100).reshape(10,10)

In [33]:
(masked_arr > 20).shape

(10, 10)

In [34]:
(masked_arr[masked_arr>20]).shape

(47,)

In [35]:
mask_int_arr = (masked_arr>20).astype('int64')

In [36]:
mask_int_arr

array([[1, 1, 1, 0, 1, 1, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 0, 0, 1, 0],
       [0, 0, 0, 1, 1, 1, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 0, 1, 0, 0, 1],
       [1, 1, 0, 0, 0, 1, 1, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 0, 1, 1, 0],
       [1, 1, 0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 1, 1, 0, 1, 0, 0, 0]])

In [37]:
mask_int_arr.shape

(10, 10)

In [38]:
any_arr = masked_arr.reshape(4,25)

In [39]:
any_arr

array([[32, 23, 27,  4, 30, 29, 14, 28, 12, 11,  1, 16,  2, 34,  3, 26,
        22, 24, 27, 24,  7, 13, 14, 17, 21],
       [32,  6, 12, 27,  4, 15, 19, 11, 39, 25, 29,  7, 13,  5, 31, 30,
        31, 20, 13, 17,  1, 23, 11,  3, 32],
       [34, 21,  5,  4,  6, 32, 22, 38, 16, 24, 35,  7, 39,  2, 26,  7,
         2, 25, 26,  7, 35, 25, 17, 24, 20],
       [13, 14,  4,  6,  9, 21,  7, 36,  4, 13, 36, 17, 37,  6, 30, 39,
         9, 37, 21, 37,  8, 31, 13, 19,  9]])

### any all

In [40]:
np.any(any_arr >20)

True

In [41]:
np.any(any_arr > 20, axis = 0)   # colum-wise comparision

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True])

In [42]:
np.any(any_arr > 20, axis = 1)   # row-wise comparision

array([ True,  True,  True,  True])

In [43]:
np.all(any_arr > 20)

False

In [44]:
np.all(any_arr > 20, axis = 0)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [45]:
np.all(any_arr > 20 , axis = 1)

array([False, False, False, False])

In [46]:
masked_arr

array([[32, 23, 27,  4, 30, 29, 14, 28, 12, 11],
       [ 1, 16,  2, 34,  3, 26, 22, 24, 27, 24],
       [ 7, 13, 14, 17, 21, 32,  6, 12, 27,  4],
       [15, 19, 11, 39, 25, 29,  7, 13,  5, 31],
       [30, 31, 20, 13, 17,  1, 23, 11,  3, 32],
       [34, 21,  5,  4,  6, 32, 22, 38, 16, 24],
       [35,  7, 39,  2, 26,  7,  2, 25, 26,  7],
       [35, 25, 17, 24, 20, 13, 14,  4,  6,  9],
       [21,  7, 36,  4, 13, 36, 17, 37,  6, 30],
       [39,  9, 37, 21, 37,  8, 31, 13, 19,  9]])

In [47]:
((masked_arr > 20) & (masked_arr < 30))

array([[False,  True,  True, False, False,  True, False,  True, False,
        False],
       [False, False, False, False, False,  True,  True,  True,  True,
         True],
       [False, False, False, False,  True, False, False, False,  True,
        False],
       [False, False, False, False,  True,  True, False, False, False,
        False],
       [False, False, False, False, False, False,  True, False, False,
        False],
       [False,  True, False, False, False, False,  True, False, False,
         True],
       [False, False, False, False,  True, False, False,  True,  True,
        False],
       [False,  True, False,  True, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False,  True, False, False, False, False, False,
        False]])

In [48]:
~((masked_arr > 20) & (masked_arr < 30))

array([[ True, False, False,  True,  True, False,  True, False,  True,
         True],
       [ True,  True,  True,  True,  True, False, False, False, False,
        False],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True],
       [ True,  True,  True,  True, False, False,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True, False,  True,  True,
         True],
       [ True, False,  True,  True,  True,  True, False,  True,  True,
        False],
       [ True,  True,  True,  True, False,  True,  True, False, False,
         True],
       [ True, False,  True, False,  True,  True,  True,  True,  True,
         True],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True, False,  True,  True,  True,  True,  True,
         True]])

### Accessing arrays

In [49]:
posi = np.arange(1,31).reshape(6,5)

In [50]:
posi

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [51]:
posi[ 2:3+1 , 0:1+1 ]

array([[11, 12],
       [16, 17]])

In [52]:
posi[ (0,1,2,3) , (1,2,3,4) ]

array([ 2,  8, 14, 20])

In [53]:
posi[ (0,-2,-1),3: ]

array([[ 4,  5],
       [24, 25],
       [29, 30]])