# Numpy

### numpy is a homogenous array it's main objective is to create multidimensional arrays and process them faster

###### Importing numpy 

In [1]:
import numpy as np

###### creating a numpy array

In [2]:
first_array = np.array([2,3,4])  # 1D array

In [3]:
first_array

array([2, 3, 4])

In [4]:
print(first_array)

[2 3 4]


##### insert and append

In [5]:
first_array

array([2, 3, 4])

In [6]:
np.insert(first_array, 3, 5)

array([2, 3, 4, 5])

In [7]:
second_arr = np.array([7,8,9])

In [8]:
np.append([[1,2,3],[4,5,6]],[7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.append([first_array],second_arr)

array([2, 3, 4, 7, 8, 9])

##### two dimensional array

In [10]:
two_D_array = np.array([
                        [1,2,3],
                        [11,22,33]
                        ])

In [11]:
two_D_array

array([[ 1,  2,  3],
       [11, 22, 33]])

In [12]:
print(two_D_array)

[[ 1  2  3]
 [11 22 33]]


###### delete

In [13]:
np.delete(two_D_array,1,0)   # axis = 0 deletes the row

array([[1, 2, 3]])

In [14]:
np.delete(two_D_array,1,1)   # axis = 1 delets the column

array([[ 1,  3],
       [11, 33]])

In [15]:
two_D_array

array([[ 1,  2,  3],
       [11, 22, 33]])

###### arange

In [16]:
my_arr = np.arange(1,11)

In [17]:
my_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
steps_arange_arr = np.arange(1,11,5)

In [19]:
print(steps_arange_arr)

[1 6]


In [20]:
steps_arange_arr = np.arange(1,5,3)

In [21]:
print(steps_arange_arr)

[1 4]


In [22]:
steps_arange_arr = np.arange(0,2,0.7)

In [23]:
print(steps_arange_arr)

[0.  0.7 1.4]


###### reshape

In [24]:
my_reshaped_arr = my_arr.reshape(5,2)      # to use reshape size must be equal to size of previous shape 

In [25]:
my_reshaped_arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [26]:
my_reshaped_arr = my_arr.reshape(2,5)    

In [27]:
my_reshaped_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

###### ndim

In [28]:
my_arr.ndim       # my_arr has one dimension 1D array (10x1)

1

In [29]:
my_reshaped_arr.ndim        # my_reshaped_arr has two dimensions 2D array (2x5)

2

###### dtype

In [30]:
my_arr.dtype

dtype('int64')

In [31]:
my_arr_dtype_example = np.arange(1,10,dtype = 'float32')

In [32]:
my_arr_dtype_example

array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [33]:
my_arr_dtype_example.dtype

dtype('float32')

In [34]:
floating_type_array = np.array([1.0,2.0,30.3])

In [35]:
floating_type_array.dtype

dtype('float64')

###### itemsize

In [36]:
my_arr.itemsize      # dtype = int64 ---> 8x8 = 64

8

In [37]:
my_arr_dtype_example.itemsize     #  dtype = float32  ---> 4x8 = 32

4

In [38]:
floating_type_array.itemsize      #  dtype = float64  ---> 8x8 = 64

8

###### type

In [39]:
type(my_arr)

numpy.ndarray

In [40]:
type(my_reshaped_arr)

numpy.ndarray

In [41]:
print(type(my_arr_dtype_example))

<class 'numpy.ndarray'>


###### complex data type

In [42]:
complex_arr = np.array([1+2j, 3+5j])

In [43]:
complex_arr.dtype

dtype('complex128')

In [44]:
complex_arr.itemsize     

16

In [45]:
array_converted_to_complex = np.array([[1,2,3],[4,5,6]], dtype = 'complex')

In [46]:
array_converted_to_complex.dtype

dtype('complex128')

###### np.zeros

In [47]:
zeros_arr = np.zeros([2,4])

In [48]:
zeros_arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
zeros_arr.dtype = 'int64'

In [50]:
zeros_arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [51]:
zeros_arr.dtype

dtype('int64')

###### np.ones

In [52]:
ones_arr = np.ones([3,2])

In [53]:
ones_arr

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [54]:
ones_arr.ndim

2

In [55]:
ones_arr.dtype

dtype('float64')

###### linspace

In [56]:
linear_spaced_arr = np.linspace(0,10,20)

In [57]:
print(linear_spaced_arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [58]:
linear_spaced_arr = np.linspace(0,1,5)

In [59]:
linear_spaced_arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

###### trignometric functions

In [60]:
from numpy import pi

In [61]:
# as we know ange 360 can be given as 2*pi

In [62]:
lineaar_spaced_100_values = np.linspace(0,2*pi,100)

In [63]:
np.sin(lineaar_spaced_100_values)

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [64]:
# np.sin( should pass correspondig radian value of the angle )

In [65]:
print(np.sin(90*pi/180))

1.0


###### $^like methods

In [66]:
np.zeros_like(my_arr)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [67]:
np.ones_like(my_reshaped_arr)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [68]:
np.full_like(my_arr_dtype_example,2)

array([2., 2., 2., 2., 2., 2., 2., 2., 2.], dtype=float32)

In [69]:
np.full_like(my_arr_dtype_example,5)

array([5., 5., 5., 5., 5., 5., 5., 5., 5.], dtype=float32)

In [70]:
np.empty_like(my_arr)    # inserts some garbage values into my_arr

array([           0,            0, 433791697006, 408021893235,
       450971566188, 433791697003, 468151435304, 408021893241,
       433791697010, 446676598899])

##### copy

In [71]:
copy_arr = np.array(first_array,copy = True)

In [72]:
copy_arr

array([2, 3, 4])

##### mat

In [73]:
matrix_array = np.array(np.mat('1 3 2; 3 4 4'))     # always (nxn) matrix cannot create (mxn)

In [74]:
matrix_array

array([[1, 3, 2],
       [3, 4, 4]])

##### asarray

In [75]:
l = [1,2,3]
m = [[22,3,4],[1,6,8]]

In [76]:
as_an_array = np.asarray(l)

In [77]:
as_an_array

array([1, 2, 3])

In [78]:
as_an_array == np.asarray(as_an_array)

array([ True,  True,  True])

##### shape 

In [79]:
as_an_array.shape

(3,)

In [80]:
two_D_array.shape

(2, 3)

##### flatten

In [81]:
two_D_array.flatten()     # row-major

array([ 1,  2,  3, 11, 22, 33])

In [82]:
two_D_array

array([[ 1,  2,  3],
       [11, 22, 33]])

In [83]:
two_D_array.flatten('F')   # column major

array([ 1, 11,  2, 22,  3, 33])

##### axis and transpose

In [84]:
axis_example_arr = np.linspace(1,37,36).reshape(3,2,6)

In [85]:
axis_example_arr.shape

(3, 2, 6)

In [86]:
np.moveaxis(axis_example_arr, 0,-1).shape

(2, 6, 3)

In [87]:
np.moveaxis(axis_example_arr, -1, 1).shape

(3, 6, 2)

In [88]:
np.swapaxes(axis_example_arr , 1,0).shape

(2, 3, 6)

In [89]:
np.transpose(axis_example_arr).shape

(6, 2, 3)

In [90]:
two_D_array.shape

(2, 3)

In [91]:
np.transpose(two_D_array).shape

(3, 2)

##### max and min

In [92]:
np.max(first_array)

4

In [93]:
np.min(two_D_array)

1

##### stack

In [94]:
x = np.array([1,2,4])
y = np.array([0,7,8])

In [95]:
np.stack((x,y))    # should pass a tuple all arrays should be of same shape

array([[1, 2, 4],
       [0, 7, 8]])

In [96]:
np.stack(x)

array([1, 2, 4])

In [97]:
z = np.array([11,22,34])

In [98]:
np.stack((x,y,z))

array([[ 1,  2,  4],
       [ 0,  7,  8],
       [11, 22, 34]])

###### ravel

In [99]:
two_D_array

array([[ 1,  2,  3],
       [11, 22, 33]])

In [100]:
np.ravel(two_D_array)

array([ 1,  2,  3, 11, 22, 33])

In [101]:
np.ravel(two_D_array,'F')

array([ 1, 11,  2, 22,  3, 33])

In [102]:
np.ravel(two_D_array,'C')

array([ 1,  2,  3, 11, 22, 33])

###### expand_dims

In [103]:
expand_dims_arr = np.linspace(1,101,36)

In [104]:
expand_dims_arr

array([  1.        ,   3.85714286,   6.71428571,   9.57142857,
        12.42857143,  15.28571429,  18.14285714,  21.        ,
        23.85714286,  26.71428571,  29.57142857,  32.42857143,
        35.28571429,  38.14285714,  41.        ,  43.85714286,
        46.71428571,  49.57142857,  52.42857143,  55.28571429,
        58.14285714,  61.        ,  63.85714286,  66.71428571,
        69.57142857,  72.42857143,  75.28571429,  78.14285714,
        81.        ,  83.85714286,  86.71428571,  89.57142857,
        92.42857143,  95.28571429,  98.14285714, 101.        ])

In [105]:
expand_dims_arr.shape

(36,)

In [106]:
np.expand_dims(expand_dims_arr, axis = 0).shape

(1, 36)

In [107]:
np.expand_dims(expand_dims_arr, axis = 1).shape

(36, 1)

##### split

In [108]:
split_arr = np.linspace(1,10,12);

In [109]:
split_arr

array([ 1.        ,  1.81818182,  2.63636364,  3.45454545,  4.27272727,
        5.09090909,  5.90909091,  6.72727273,  7.54545455,  8.36363636,
        9.18181818, 10.        ])

In [110]:
print(np.split(split_arr,3))     # returns a list of numpy_array_objects
print("length is ",len(np.split(split_arr,3)))

[array([1.        , 1.81818182, 2.63636364, 3.45454545]), array([4.27272727, 5.09090909, 5.90909091, 6.72727273]), array([ 7.54545455,  8.36363636,  9.18181818, 10.        ])]
length is  3


In [111]:
print(np.split(split_arr,4))     
print("length is ",len(np.split(split_arr,4)))

[array([1.        , 1.81818182, 2.63636364]), array([3.45454545, 4.27272727, 5.09090909]), array([5.90909091, 6.72727273, 7.54545455]), array([ 8.36363636,  9.18181818, 10.        ])]
length is  4


In [112]:
print(np.split(split_arr,6))     
print("length is ",len(np.split(split_arr,6)))

[array([1.        , 1.81818182]), array([2.63636364, 3.45454545]), array([4.27272727, 5.09090909]), array([5.90909091, 6.72727273]), array([7.54545455, 8.36363636]), array([ 9.18181818, 10.        ])]
length is  6


In [113]:
np.array_split(split_arr,5)

[array([1.        , 1.81818182, 2.63636364]),
 array([3.45454545, 4.27272727, 5.09090909]),
 array([5.90909091, 6.72727273]),
 array([7.54545455, 8.36363636]),
 array([ 9.18181818, 10.        ])]

##### hsplit and vsplit

In [114]:
split_arr.shape

(12,)

In [115]:
splits_arr = np.arange(1,17).reshape(4,4)

In [116]:
splits_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [117]:
np.vsplit(splits_arr,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [118]:
np.hsplit(splits_arr,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

##### trim_zeros

In [119]:
trim_arr = np.array([0,0,1,2,3,0])

In [120]:
np.trim_zeros(trim_arr)

array([1, 2, 3])