In [1]:
import numpy as np

In [2]:
l = [[1,2,3],[4,5,6],[7,8,9]]
a = np.array(l)

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
a+3

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [5]:
a*3

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [6]:
def fun(x,p):
    return x**p
a = fun(a,2)

In [15]:
a

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [16]:
l = [1,2,3]
b = np.array(l)

In [17]:
a+b

array([[ 2,  6, 12],
       [17, 27, 39],
       [50, 66, 84]])

In [19]:
print(a.shape)
print(b.shape)
np.dot(a,b) 

(3, 3)
(3,)


array([ 36, 174, 420])

In [20]:
fruits = [[56.0,0.0,4.4,68.0],[1.2,104.0,52.0,8.0],[1.8,135.0,99.0,0.9]]

In [21]:
fr = np.array(fruits)

In [22]:
fr

array([[ 56. ,   0. ,   4.4,  68. ],
       [  1.2, 104. ,  52. ,   8. ],
       [  1.8, 135. ,  99. ,   0.9]])

In [23]:
sum_col = fr.sum(axis = 0)

In [24]:
sum_col

array([ 59. , 239. , 155.4,  76.9])

In [26]:
print(sum_col.shape)
print(fr.shape)
#percent = (fr/sum_col)*100

(4,)
(3, 4)


In [27]:
sum_col = sum_col.reshape(1,4)

In [31]:
col_sum = fr.sum(axis =  0)

In [35]:
percent = (fr/col_sum)*100
col_sum.shape
col_sum

array([ 59. , 239. , 155.4,  76.9])

In [33]:
percent

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

In [37]:
array1d = np.array([1,2,3,4])
print("shape of array1d before reshaping: ", array1d.shape)
array1d = array1d.reshape(1,4)
print("shape of array1d after reshaping: ", array1d.shape)
#rank of matrix can be found using np.linalg.matrix_rank() function
print("array1d is a martrix of rank {}".format(np.linalg.matrix_rank(array1d)))

shape of array1d before reshaping:  (4,)
shape of array1d after reshaping:  (1, 4)
array1d is a martrix of rank 1
